### ISSUE TITLE
need help with -gcol param

### ISSUE THREAD

**Issue by lucast122** [iquasere/KEGGCharter#1]
Your tool seems very useful for me, but I don't really understand what the -gcol param should specify. I tried out the example data and the example call provided in the readme, but it gives me an exception:
`KeyError: "Columns not found: 'mg'"`
which makes sense to me, as I also couldn't find that specific column in the example data.
Could you please clarify this for me? 

Edit:

the command call I used:
`python3 keggcharter.py -f MOSCA_Entry_Report.xlsx -gcol Entry -tcol mt_0.01a_normalized,mt_1a_normalized,mt_100a_normalized,mt_0.01b_normalized,mt_1b_normalized,mt_100b_normalized,mt_0.01c_normalized,mt_1c_normalized,mt_100c_normalized -keggc "Cross-reference (KEGG)" -o test_keggcharter -tc "Taxonomic lineage (GENUS)"`

**Comment by iquasere** [comment]
Hi there! Glad to see interest in the tool. The right command would be setting ```pretty_commune``` as the input to the ```-gcol``` parameter, since it is the name of the column with the metagenomics quantification. The command would thus be
```
python3 keggcharter.py -f MOSCA_Entry_Report.xlsx -gcol pretty_commune -tcol mt_0.01a_normalized,mt_1a_normalized,mt_100a_normalized,mt_0.01b_normalized,mt_1b_normalized,mt_100b_normalized,mt_0.01c_normalized,mt_1c_normalized,mt_100c_normalized -keggc "Cross-reference (KEGG)" -o test_keggcharter -tc "Taxonomic lineage (GENUS)"
```
Hope it helps, please let me know if it still fails!

**Comment by lucast122** [comment]
Thank you very much, it runs now. I would have only one more question. Could you clarify how the numerical value of the genomics column for each protein is computed, or what it describes? For transcriptomics, it makes sense to me, but not for the genomics part.

**Comment by iquasere** [comment]
When running KEGGCharter, ```-gcol``` is always required. As you can see, it quantifies the presence of the specific protein in the metagenome. This column is only used to quantify most abundant organisms (through the taxonomic column, it sums all values of ```-gcol```) and to identify presence/absence of proteins, i.e., proteins with no value or a value of 0 will be ignored when creating the "genomic potential" maps (those with the different taxa distinguished.

If such column is not available, a quantification of 1 can be inputed (for all proteins) with the argument ```--input-quantification```. This will have the consequence of attributing the highest abundance to the taxa with more proteins, and will represent all proteins available in the dataset (since all will have a quantification of 1).

**Comment by lucast122** [comment]
Thank you for the detailed explanation, that helps me a lot.

**Comment by GaioTransposon** [comment]
Hi Joao, 

If gcol is the genome abundance, how come in your Mosca file different values are given in the gcol column (mg) for the same species? 
Example: Methanobacterium formicicum often has got "1.88054" value, but sometimes a different value is assigned.

**Comment by iquasere** [comment]
Hey there, @GaioTransposon! Not sure what MOSCA file you are talking about, but if it is the "Protein Report", this is likely because different proteins of the same organism have different abundances quantified, i.e., more reads were mapped to one gene than the other. The file is divided by proteins, not taxa.
