### ISSUE TITLE
Missing 1 species and nothing is highlighted

### ISSUE THREAD

**Issue by Calvin2077** [iquasere/KEGGCharter#11]
Hello 

I am using Keggcharter (v. 0.5) to compare the metabolic potential (using KEGG Orthology only) between four species of archaea. The file that I am using is attached below (Book13)[Book13.xlsx](https://github.com/iquasere/KEGGCharter/files/11546078/Book13.xlsx). 

The code I am using to run Keggcharter is keggcharter.py -f Book13.xlsx -o kcar -koc "KO_ids" -tc "Taxonomic lineage (SPECIES)" --input-quantification --metabolic-maps 00020 

(I am just running the map for TCA (00020) cycle as a proof of concept for my supervisor).

While the program runs without problem when I look at my results I notice I only have 3 out of 4 species, but also none of the blocks are highlighted even though from manually searching the KEGG Orthology I do have some of the enzymes from the TCA cycle. 
 
![potential_Citrate cycle (TCA cycle)](https://github.com/iquasere/KEGGCharter/assets/72618537/e5a387dd-5a25-44b8-a919-2ac860ea137c)

Therefore if I could please have some help in solving this problem it would be greatly appreciated. 

Thank you very much

**Comment by iquasere** [comment]
Everything on your end is correct. However, I see two problems with the taxonomies you are inputting:
- "arcticus" is too vague. There are three "arcticus" in [KEGG Genomes](https://www.genome.jp/kegg-bin/show_organism?category=Prokaryotes), and KEGGCharter won't be able to determine which one is it. You only need to add the genus, and that is fixed.
- a second problem is that the "hydrocola" species is not on KEGG Genomes. That is the one missing on the maps.

The reason why the boxes are not appearing might be because KEGGCharter downloads species specific KGMLs, which usually contain much less functions identified. This is to avoid representing functions that organisms do not perform, since KEGG Orthologs are promiscuous (i.e., the same KO maps to many functions). However, there is often data missing at KEGG, so this might be having a negative effect on the results here.

Tomorrow I'll take a closer look at the data here. I should have already launched a version of KEGGCharter allowing to disregard inputted taxonomy, i.e., using the same maps for all species, and representing all the functions of all the KOs. This might give a closer picture to what you are seeing at KEGG mapper, if taxonomy is not being inputted there.

**Comment by Calvin2077** [comment]
Thank you for getting back to me so quickly and for your it is much appreciated. In regards to the two problems, can KeggCharter only use organisms that are present within the KEGG Genomes list (the link you provided)? 

Also thank you for telling me why the data might not be appearing it is appreciated. In regards to your 3rd paragraph do you mean that even if my species isn't in the KEGG Genomes list as long as I provide KOs KEGG Charter can be run and generate maps? My apologizes if I am wrong.

Thanks again for the help.

**Comment by iquasere** [comment]
> In regards to the two problems, can KeggCharter only use organisms that are present within the KEGG Genomes list (the link you provided)?

Not only those but also [Eukaryotes](https://www.genome.jp/kegg-bin/show_organism?category=Eukaryotes). KEGGCharter obtains KGMLs specific for those taxa, which it requires to know which functions each organism has. KOs are not enough to know this, since each KO maps to several functions, and some of those are not performed by some taxa. I haven't used KEGG's tools for mapping in some time, but as far as I know, one must be careful when using them, since it must be certain mapping is being performed with consideration to taxonomy (i.e., if you only give KOs to KEGG Mapper, it will map everything for those KOs, even though some functions might not be available for your particular species).

> In regards to your 3rd paragraph do you mean that even if my species isn't in the KEGG Genomes list as long as I provide KOs KEGG Charter can be run and generate maps?

I am going to work on this next. KEGGCharter should both:
1. provide the option to ignore taxon specific KGMLs - just paint everything for the KOs, even if those functions are not identified as being performed by those species, since information is often lacking;
2. paint species not available in KEGG genomes. This would follow a similar approach as 1., but only for the taxa for which there is no species specific information.

For now, KEGGCharter does neither. Only paints organisms for which there are KGMLs. 

I have also identified and fixed the bug you complained about. It was an error on KEGGCharter's part. Only functions for arcticus were identified, though. 

![potential_Citrate cycle (TCA cycle)](https://github.com/iquasere/KEGGCharter/assets/16226371/b39ca676-5332-4f99-8d2f-3d7e4b0b11f1)

I'm going to launch version `0.5.1` today to fix this, but in a coming soon `0.6` version (likely next week), these additional options for a more relaxed approach to species specific KGMLs will be implemented. Stay tuned!

**Comment by iquasere** [comment]
I've commited it but can't yet launch this next version, KEGGCharter 0.6 will be able to map all functions in disregards to taxa specific KGMLs with the option `--map-all`

![potential_Citrate cycle (TCA cycle)](https://github.com/iquasere/KEGGCharter/assets/16226371/3218a7fd-6451-4ce4-af80-10feb21e809e)

and also to map the functions of taxa not present in KEGG Genomes with the option `--include-missing-genomes`

![potential_Citrate cycle (TCA cycle)](https://github.com/iquasere/KEGGCharter/assets/16226371/67a3b650-5bf5-4807-8acf-a52d4d3af6b5)

**Comment by Calvin2077** [comment]
Absolutely fantastic!!! Thank you so much for all your help in answering my questions and for making improvements to the package to accommodate my projects it is very much appreciated and means a lot so thank you very much.

If I can ask, when do you think you will be able to launch the newest version? 

Thanks again!

**Comment by Calvin2077** [comment]
I see you have already updated it so I thank you so very much for working so quickly to make these updates so thank you so much and I hope you have a wonderful week!!

**Comment by iquasere** [comment]
No problem, always happy to get user feedback to improve the tool! If you could also compare these results with the ones you got using the tools at KEGG, are there functions missing? Or is the map with `--include-missing-genomes` representing all functions represented with KEGG tools?
