### ISSUE TITLE
Usage with eggnog-mapper output

### ISSUE THREAD

**Issue by Lucas-Maciel** [iquasere/KEGGCharter#2]
Hello,

I just read your paper showing the UPIMAPI, reCOGnizer and KEGGChart tools and found it very interesting. 

I intend to test your UPIMAPI/reCOGnizer annotation pipeline in future projects, however, I have a gene catalog with 10 million proteins that was already annotated with eggnog-mapper and I have been using this annotation to make all my analysis. Is there an easy way to use visualize the eggnog-mapper results in this KEGGCharter tool?

Thank you for your time
Kind regards
Lucas

**Comment by iquasere** [comment]
Greetings, Lucas! To be run, KEGGCharter needs a column with functional IDs - either KEGG IDs, KOs or EC numbers. Since eggNOG-Mapper returns EC numbers, you can use those as input to the tool (specifying the option ```-ecc```). Then, there are many optional parameters that will enhance experience:
* providing a list of maps with ```-mm``` will let you decide what maps you want to visualize (e.g. ```-mm 00190,00680```)
* providing a taxonomic column with ```-tc``` will allow to represent taxonomy in the maps (e.g. ```-tc 'Taxonomic lineage (SPECIES)'```
* this option relates with the ````-gcol```, used to determine main actors (by level of quantification)
* providing taxonomic columns will allow to represent differential expression in the maps (e.g. ```-tcol mt_0.01a,mt_1a,mt_100a,mt_0.01b,mt_1b,mt_100b,mt_0.01c,mt_1c,mt_100c```)

Where some of these informations are not provided, KEGGCharter will use default parameters. For the case of ```-tcol``` and ```-gcol```, if not set, the ```-it``` and ```-iq``` must be set, so KEGGCharter will input values to use as replacements.
